name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    name: Building and Pushing the Image
    runs-on: ubuntu-latest

    env:
      IMGTAG: ${{ github.run_number }}
      USERNAME: ${{ secrets.DOCKERUSER }}
      PASSWORD: ${{ secrets.DOCKERPW }}

    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: "$USERNAME"
          password: "$PASSWORD"

      - name: Publish to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: karimniang/demo-github-actions:$IMGTAG

      # - name: Buil & Push Image
      #   run: |
      #     docker image build -t karimniang/demo-github-actions:$IMGTAG .
      #     docker push karimniang/demo-github-actions:$IMGTAG
