name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    name: Building and Pushing the Image
    runs-on: ubuntu-latest

    env:
      IMGTAG: ${{ github.run_number }}

    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERUSER }}
          password: ${{ secrets.DOCKERPW }}

      - name: Buil & Push Image
        id: check1
        run: |
          docker image build -t karimniang/demo-github-actions:$IMGTAG .
          docker push karimniang/demo-github-actions:$IMGTAG
      - name: test
        run: echo ${{ steps.last_status.outputs.last_status }}
    outputs:
      statusBuild: ${{ steps.last_status.outputs.last_status }}

  notify-slack:
    if: ${{ always() }}
    needs: build
    name: Slack Notifications
    runs-on: ubuntu-latest
    #   #environment: Slackbot Notification
    steps:
      - name: Notification slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: test-github-actions
          SLACK_TITLE: Test Github action
          SLACK_USERNAME: Abdou Karim Niang
          SLACK_WEBHOOK: ${{ secrets.WEBHOOKURL }}
          SLACK_MESSAGE: ${{ needs.build.outputs.statusBuild }}
          SLACK_COLOR: ${{ needs.build.outputs.statusBuild }}
      - name: test
        run: echo ${{ needs.build.outputs.statusBuild }}
