name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    name: Building and Pushing the Image
    runs-on: ubuntu-latest

    env:
      IMGTAG: ${{ github.run_number }}
      DOCKERPWD: ${{ secrets.DOCKERPW }}

    steps:
      - uses: actions/checkout@v1
      - name: Buil & Push Image
        run: |
          echo "$DOCKERPWD" | docker login -u "karimniang" --password-stdin
          docker image build -t karimniang/demo-github-actions:$IMGTAG .
          docker push karimniang/demo-github-actions:$IMGTAG
